# Source: hello-world/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-hello-world
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/version: "1.16.0"